### ISSUE TITLE
Module is not actually "Tiny"

### ISSUE THREAD

**Issue by robrwo** [robrwo/Net-Statsd-Tiny#2]
From joshua@keroes.com:

> After looking through the implementation, I think this module might work better with module name
> tweak. Would you consider that? Not because there's anything competing for the name you've
> chosen but because modules that use the "Tiny" moniker implies that it can be run without installing
> any other modules.

After thinking about this, I am inclined to agree.

I think renaming this module to Net::Statsd::Lite is appropriate, but then keeping the Tiny module as a separate release that doesn't use the Moo/Type::Tiny stack.

**Comment by robrwo** [comment]
This is a work in progress.

**Comment by jkeroes** [comment]
Looks good!

**Comment by robrwo** [comment]
Fixed in v0.3.0. The tests still use Test::Roo etc though.
